<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Hash;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('answer_options')->truncate();
        DB::table('questions')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('questions')->insert([
            [
                'id' => 1,
                'dimension_id' => 1,
                'question_text' => 'What is the status of your organization\'s AI strategy?',
                'order' => 1,
                'weight' => 1,
                'help_text' => 'hyuijk',
                'is_active' => 1,
                'created_at' => '2026-07-04 12:02:08',
                'updated_at' => '2026-07-05 11:33:32',
            ],
            [
                'id' => 2,
                'dimension_id' => 1,
                'question_text' => 'How is AI investment prioritized within the organization?',
                'order' => 2,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:03:15',
                'updated_at' => '2026-07-05 11:33:49',
            ],
            [
                'id' => 3,
                'dimension_id' => 1,
                'question_text' => 'How does your organization monitor the external AI landscape?',
                'order' => 2,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:03:33',
                'updated_at' => '2026-07-05 12:56:25',
            ],
            [
                'id' => 4,
                'dimension_id' => 2,
                'question_text' => 'How would you characterize the quality of data available for AI use cases?',
                'order' => 4,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:03:54',
                'updated_at' => '2026-07-04 12:03:54',
            ],
            [
                'id' => 5,
                'dimension_id' => 2,
                'question_text' => 'Does the organization maintain a data catalogue covering AI-relevant datasets?',
                'order' => 5,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:04:12',
                'updated_at' => '2026-07-04 12:04:12',
            ],
            [
                'id' => 6,
                'dimension_id' => 2,
                'question_text' => 'How is personal data managed in compliance with applicable regulations?',
                'order' => 5,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:04:36',
                'updated_at' => '2026-07-04 12:04:36',
            ],
            [
                'id' => 7,
                'dimension_id' => 4,
                'question_text' => 'Does the organization have a formal AI governance body?',
                'order' => 7,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:05:03',
                'updated_at' => '2026-07-04 12:05:03',
            ],
            [
                'id' => 8,
                'dimension_id' => 4,
                'question_text' => 'How are AI risks identified, assessed, and managed?',
                'order' => 7,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:05:46',
                'updated_at' => '2026-07-04 12:05:46',
            ],
            [
                'id' => 9,
                'dimension_id' => 4,
                'question_text' => 'Is the organization\'s AI portfolio aligned with ISO/IEC 42001:2023?',
                'order' => 8,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:06:03',
                'updated_at' => '2026-07-04 12:06:03',
            ],
            [
                'id' => 10,
                'dimension_id' => 5,
                'question_text' => 'Does the organization have an operationalized Responsible AI policy?',
                'order' => 11,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:06:17',
                'updated_at' => '2026-07-04 12:06:17',
            ],
            [
                'id' => 11,
                'dimension_id' => 5,
                'question_text' => 'How does the organization test AI systems for bias and fairness?',
                'order' => 12,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:06:33',
                'updated_at' => '2026-07-04 12:06:33',
            ],
            [
                'id' => 12,
                'dimension_id' => 10,
                'question_text' => 'Is a structured change management methodology applied to AI programme delivery?',
                'order' => 12,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:07:32',
                'updated_at' => '2026-07-04 12:07:32',
            ],
            [
                'id' => 13,
                'dimension_id' => 10,
                'question_text' => 'How does the organization measure AI adoption?',
                'order' => 13,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:07:46',
                'updated_at' => '2026-07-04 12:07:46',
            ],
            [
                'id' => 14,
                'dimension_id' => 11,
                'question_text' => 'Has the organization performed threat modelling specific to its AI systems?',
                'order' => 15,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:08:03',
                'updated_at' => '2026-07-04 12:08:03',
            ],
            [
                'id' => 15,
                'dimension_id' => 11,
                'question_text' => 'How does the organization manage prompt injection and adversarial input risks?',
                'order' => 16,
                'weight' => 1,
                'help_text' => null,
                'is_active' => 1,
                'created_at' => '2026-07-04 12:08:19',
                'updated_at' => '2026-07-04 12:08:19',
            ],
        ]);

        DB::table('answer_options')->insert([
            [
                'id' => 1,
                'question_id' => 1,
                'label' => 'No AI strategy exists and none is planned.',
                'score' => 1,
                'order' => 1,
                'created_at' => '2026-07-04 12:10:19',
                'updated_at' => '2026-07-04 12:52:22',
            ],
            [
                'id' => 2,
                'question_id' => 1,
                'label' => 'AI strategy discussions have occurred at senior level but nothing is documented or approved.',
                'score' => 2,
                'order' => 2,
                'created_at' => '2026-07-04 12:10:19',
                'updated_at' => '2026-07-04 12:52:22',
            ],
            [
                'id' => 3,
                'question_id' => 1,
                'label' => 'An AI strategy document exists and has been approved by senior leadership.',
                'score' => 3,
                'order' => 3,
                'created_at' => '2026-07-04 12:10:19',
                'updated_at' => '2026-07-04 12:52:22',
            ],
            [
                'id' => 4,
                'question_id' => 1,
                'label' => 'A board-approved AI strategy exists, is linked to the business strategy, has a funded multi-year roadmap, and is subject to regular executive review.',
                'score' => 4,
                'order' => 4,
                'created_at' => '2026-07-04 12:10:19',
                'updated_at' => '2026-07-04 12:52:22',
            ],
            [
                'id' => 5,
                'question_id' => 2,
                'label' => 'aa',
                'score' => 1,
                'order' => 1,
                'created_at' => '2026-07-05 11:33:49',
                'updated_at' => '2026-07-05 11:33:49',
            ],
            [
                'id' => 6,
                'question_id' => 2,
                'label' => 'nb',
                'score' => 2,
                'order' => 2,
                'created_at' => '2026-07-05 11:33:49',
                'updated_at' => '2026-07-05 11:33:49',
            ],
            [
                'id' => 7,
                'question_id' => 2,
                'label' => 'r',
                'score' => 3,
                'order' => 3,
                'created_at' => '2026-07-05 11:33:49',
                'updated_at' => '2026-07-05 11:33:49',
            ],
            [
                'id' => 8,
                'question_id' => 2,
                'label' => 'f',
                'score' => 4,
                'order' => 4,
                'created_at' => '2026-07-05 11:33:49',
                'updated_at' => '2026-07-05 11:33:49',
            ],
            [
                'id' => 9,
                'question_id' => 3,
                'label' => 'ddddd',
                'score' => 1,
                'order' => 1,
                'created_at' => '2026-07-05 12:56:25',
                'updated_at' => '2026-07-05 12:56:25',
            ],
            [
                'id' => 10,
                'question_id' => 3,
                'label' => 'xx',
                'score' => 2,
                'order' => 2,
                'created_at' => '2026-07-05 12:56:25',
                'updated_at' => '2026-07-05 12:56:25',
            ],
            [
                'id' => 11,
                'question_id' => 3,
                'label' => 'r',
                'score' => 3,
                'order' => 3,
                'created_at' => '2026-07-05 12:56:25',
                'updated_at' => '2026-07-05 12:56:25',
            ],
            [
                'id' => 12,
                'question_id' => 3,
                'label' => 'f',
                'score' => 4,
                'order' => 4,
                'created_at' => '2026-07-05 12:56:25',
                'updated_at' => '2026-07-05 12:56:25',
            ],
        ]);
    }
}
