<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Adds the fields required to store
     * the AI-generated executive summary.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('assessments', function (Blueprint $table) {

            // Executive summary generated by the AI model
            $table->longText('ai_executive_summary')
                ->nullable();

            // not_generated | generated | failed
            $table->string('ai_summary_status')
                ->default('not_generated');

            // AI model used to generate the summary
            $table->string('ai_summary_model')
                ->nullable();

            // Date and time of the latest successful generation
            $table->timestamp('ai_summary_generated_at')
                ->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('assessments', function (Blueprint $table) {

            $table->dropColumn([
                'ai_executive_summary',
                'ai_summary_status',
                'ai_summary_model',
                'ai_summary_generated_at',
            ]);
        });
    }
};